### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by taketaku** [taketaku/til#1]
- [ ] create React + Redux Sample app
- [ ] touch GraphQL
- [ ] create Nuxt.js Sample app
- [ ] touch gRPC
- [ ] create CREDIT CARD PAYMENT SYSTEM Sample app with Golang, SPA
